version: '1.0'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A DistrictChampion worker --loglevel=info
    depends_on:
      - redis
    environment:
      - DEBUG=False

  celery-beat:
    build: .
    command: celery -A DistrictChampion beat --loglevel=info
    depends_on:
      - redis
    environment:
      - DEBUG=False

  redis:
    image: redis:7
    ports:
      - "6380:6379"
