services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
    depends_on:
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    command: celery -A DistrictChampion worker --loglevel=info
    volumes:               
      - .:/app
    depends_on:
      - redis
    environment:
      - DEBUG=False

  celery-beat:
    build: .
    command: celery -A DistrictChampion beat --loglevel=info
    volumes:                
      - .:/app
    depends_on:
      - redis
    environment:
      - DEBUG=False

  redis:
    image: redis:7
    ports:
      - "6385:6379"
