# Generated by Django 5.2.1 on 2025-06-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('prop_1', models.CharField(blank=True, max_length=50, null=True)),
                ('prop_2', models.CharField(blank=True, max_length=50, null=True)),
                ('prop_3', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('owners', models.ManyToManyField(blank=True, related_name='cards', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('match_date', models.DateTimeField()),
                ('match_type', models.CharField(max_length=50)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='players.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='players.player')),
            ],
        ),
    ]
