# Generated by Django 5.2.1 on 2025-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
