# Generated by Django 5.2.1 on 2025-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playingcard_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='team',
            field=models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
