# Generated by Django 5.2.1 on 2025-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playingcard_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
